CREATE TABLE `PERSONA` (
	`ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `NOMBRE` VARCHAR(20) NOT NULL,
    `PRIMER_APELLIDO` VARCHAR(20) NOT NULL,
    `SEGUNDO_APELLIDO` VARCHAR(20),
    `CORREO` VARCHAR(255) NOT NULL,
    `LOGIN` VARCHAR(60) NOT NULL,
    `PASSWORD` VARCHAR(8) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
